# Generated by Django 4.2.4 on 2023-09-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="quantity_desired",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
