# Generated by Django 4.2.4 on 2023-09-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_alter_item_price_alter_item_quantity_desired"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gift",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
